
"""Superstore_Analyse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gRFe13i4QA2v8xiz0VRZ0bEVuZFAswDw
"""

# ========== ÉTAPE 1: CHARGEMENT ==========
import pandas as pd
import numpy as np
from google.colab import files

# Télécharge le fichier
print("📥 Télécharge le fichier 'Sample - Superstore.csv'")
uploaded = files.upload()

# Charge les données
df = pd.read_csv('Sample - Superstore.csv', encoding='latin1')
print(f"✅ Données chargées: {df.shape[0]} lignes x {df.shape[1]} colonnes")
print(df.head())

# ========== ÉTAPE 2: NETTOYAGE ==========
print("\n🧹 NETTOYAGE DES DONNÉES...")

# Conversion des dates
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

# Extraction des composants temporels
df['Order Year'] = df['Order Date'].dt.year
df['Order Month'] = df['Order Date'].dt.month
df['Order Quarter'] = df['Order Date'].dt.quarter
df['Order Weekday'] = df['Order Date'].dt.day_name()

# Calculs additionnels
df['Shipping Days'] = (df['Ship Date'] - df['Order Date']).dt.days
df['Profit Margin %'] = (df['Profit'] / df['Sales'] * 100).round(2)

print("✅ Nettoyage terminé")
print(f"Colonnes ajoutées: {list(df.columns[-6:])}")

# ========== ÉTAPE 3: CONFIGURATION SQL CORRECTE ==========
print("\n⚙️ CONFIGURATION SQL...")
!pip install pandasql -q
from pandasql import sqldf

# FONCTION CORRIGÉE - Version qui marche
def run_sql(query):
    """Exécute une requête SQL sur le DataFrame df"""
    return sqldf(query, globals())

# Test simple
test_query = "SELECT COUNT(*) as total_rows FROM df"
test_result = run_sql(test_query)
print(f"✅ SQL configuré - Test réussi: {test_result['total_rows'][0]} lignes")

# ========== ÉTAPE 4: REQUÊTE 1 - PERFORMANCE MENSUELLE ==========
print("\n📈 REQUÊTE 1: Performance mensuelle")

query1 = """
SELECT
    strftime('%Y-%m', "Order Date") as Month,
    ROUND(SUM(Sales), 2) as Monthly_Sales,
    ROUND(SUM(Profit), 2) as Monthly_Profit,
    ROUND(AVG("Profit Margin %"), 2) as Avg_Margin_Percent,
    COUNT(DISTINCT "Order ID") as Number_of_Orders
FROM df
GROUP BY Month
ORDER BY Month
"""

# UTILISE run_sql() au lieu de pysqldf()
result1 = run_sql(query1)

print("📊 Résultats:")
print(result1.head(12))  # Affiche 12 mois
print(f"\n🔝 Meilleur mois (CA): {result1.loc[result1['Monthly_Sales'].idxmax(), 'Month']}")
print(f"📉 Moins bon mois (marge): {result1.loc[result1['Avg_Margin_Percent'].idxmin(), 'Month']} ({result1['Avg_Margin_Percent'].min()}%)")

# ========== ÉTAPE 5: REQUÊTE 2 - TOP CLIENTS ==========
print("\n👥 REQUÊTE 2: Analyse des clients")

query2 = """
SELECT
    "Customer ID",
    "Customer Name",
    COUNT(DISTINCT "Order ID") as Total_Orders,
    ROUND(SUM(Sales), 2) as Total_Spent,
    ROUND(SUM(Profit), 2) as Total_Profit,
    ROUND(AVG("Profit Margin %"), 2) as Avg_Margin
FROM df
GROUP BY "Customer ID", "Customer Name"
ORDER BY Total_Spent DESC
LIMIT 10
"""

result2 = run_sql(query2)
print(result2)

# ========== ÉTAPE 6: REQUÊTE 3 - PRODUITS PERFORMANTS ==========
print("\n📦 REQUÊTE 3: Top produits")

query3 = """
SELECT
    "Product ID",
    "Product Name",
    Category,
    "Sub-Category",
    ROUND(SUM(Sales), 2) as Total_Sales,
    ROUND(SUM(Profit), 2) as Total_Profit,
    SUM(Quantity) as Total_Quantity_Sold,
    COUNT(DISTINCT "Order ID") as Times_Ordered
FROM df
GROUP BY "Product ID", "Product Name", Category, "Sub-Category"
ORDER BY Total_Sales DESC
LIMIT 15
"""

result3 = run_sql(query3)
print(result3)

# ========== REQUÊTE 4 CORRIGÉE ==========
print("\n🌎 REQUÊTE 4: Performance géographique")
query4 = """
SELECT
    Region,
    State,
    COUNT(DISTINCT "Order ID") as Order_Count,
    ROUND(SUM(Sales), 2) as Total_Sales,
    ROUND(SUM(Profit), 2) as Total_Profit,
    ROUND(AVG("Profit Margin %"), 2) as Avg_Margin,
    ROUND(AVG("Shipping Days"), 1) as Avg_Shipping_Days
FROM df
GROUP BY Region, State
ORDER BY Total_Profit DESC
LIMIT 10
"""
result4 = run_sql(query4)
print(result4)

# ========== REQUÊTE 5 CORRIGÉE ==========
print("\n📅 REQUÊTE 5: Performance par jour de semaine")
query5 = """
SELECT
    "Order Weekday",
    COUNT(DISTINCT "Order ID") as Orders_Count,
    ROUND(SUM(Sales), 2) as Total_Sales,
    ROUND(AVG(Sales), 2) as Avg_Order_Value,
    ROUND(AVG("Profit Margin %"), 2) as Avg_Margin
FROM df
GROUP BY "Order Weekday"
ORDER BY
    CASE "Order Weekday"
        WHEN 'Monday' THEN 1
        WHEN 'Tuesday' THEN 2
        WHEN 'Wednesday' THEN 3
        WHEN 'Thursday' THEN 4
        WHEN 'Friday' THEN 5
        WHEN 'Saturday' THEN 6
        WHEN 'Sunday' THEN 7
    END
"""
result5 = run_sql(query5)
print(result5)

print("📊 PRÉPARATION DES DONNÉES POUR TABLEAU...")

# 1. Créer une vue mensuelle (pour les séries temporelles)
monthly_sales = df.groupby(['Order Year', 'Order Month']).agg({
    'Sales': 'sum',
    'Profit': 'sum',
    'Quantity': 'sum',
    'Order ID': 'nunique'
}).reset_index()
monthly_sales['Year-Month'] = monthly_sales['Order Year'].astype(str) + '-' + monthly_sales['Order Month'].astype(str).str.zfill(2)

# 2. Créer une vue par catégorie
category_sales = df.groupby(['Category', 'Sub-Category']).agg({
    'Sales': 'sum',
    'Profit': 'sum',
    'Profit Margin %': 'mean',
    'Quantity': 'sum'
}).reset_index()

# 3. Créer une vue géographique
geo_sales = df.groupby(['Region', 'State', 'City']).agg({
    'Sales': 'sum',
    'Profit': 'sum',
    'Order ID': 'nunique'
}).reset_index()

# 4. Créer une vue produits
top_products = df.groupby(['Product ID', 'Product Name', 'Category']).agg({
    'Sales': 'sum',
    'Profit': 'sum',
    'Quantity': 'sum'
}).reset_index()
top_products = top_products.sort_values('Sales', ascending=False).head(50)

# 5. Exporter vers Excel (plusieurs feuilles)
with pd.ExcelWriter('superstore_tableau.xlsx') as writer:
    df.to_excel(writer, sheet_name='Données_Brutes', index=False)
    monthly_sales.to_excel(writer, sheet_name='Ventes_Mensuelles', index=False)
    category_sales.to_excel(writer, sheet_name='Par_Catégorie', index=False)
    geo_sales.to_excel(writer, sheet_name='Par_Région', index=False)
    top_products.to_excel(writer, sheet_name='Top_Produits', index=False)

print("✅ Fichier Excel créé avec 5 feuilles :")
print("1. Données_Brutes - Toutes les données nettoyées")
print("2. Ventes_Mensuelles - Pour graphiques temporels")
print("3. Par_Catégorie - Pour graphiques catégoriels")
print("4. Par_Région - Pour cartes géographiques")
print("5. Top_Produits - Top 50 produits")

# Télécharger le fichier
from google.colab import files
files.download('superstore_tableau.xlsx')

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from datetime import datetime

print("🚀 INITIALISATION DU DASHBOARD SUPERSETORE...")
print("="*60)

# === 1. CRÉATION DU DATASET COMPLET ===
np.random.seed(42)
n = 5000

# Dates aléatoires
dates = pd.date_range('2014-01-01', '2017-12-31', periods=n)

# Définir les sous-catégories et produits par catégorie
sub_categories = {
    'Furniture': ['Chairs', 'Tables', 'Bookcases', 'Furnishings'],
    'Office Supplies': ['Storage', 'Art', 'Binders', 'Appliances', 'Paper', 'Envelopes', 'Labels', 'Fasteners'],
    'Technology': ['Phones', 'Copiers', 'Accessories', 'Machines']
}

products = {
    'Chairs': ['Hon Deluxe Fabric Task Chair', 'Global Deluxe Steno Chair'],
    'Tables': ['Bretford Rectangular Conference Table', 'Bevis Round Conference Table'],
    'Bookcases': ['Bush Somerset Collection Bookcase', 'Sauder Camden County Collection Bookcase'],
    'Furnishings': ['Eldon Expressions Desk Accessory', 'DAX Solid Wood Frames'],
    'Storage': ['Sturdivant Sound Personal File', 'Eldon Portable Mobile Manager'],
    'Art': ['Newell 322', 'Boston 1680 Electric Pencil Sharpener'],
    'Binders': ['Durable Binders', 'GBC Binding covers'],
    'Appliances': ['Fellowes Advanced Computer Series', 'Honeywell Enviracaire Portable Air Purifier'],
    'Paper': ['Xerox 194', 'Adams Message Book'],
    'Envelopes': ['#10-4 1/8" x 9 1/2" Security-Tint Envelopes', 'Tyvek Side-Opening Envelopes'],
    'Labels': ['Avery 49', 'Avery 51'],
    'Fasteners': ['Staple envelope', 'Staples'],
    'Phones': ['Cisco Smart Phone', 'Mitel 5320 IP Phone'],
    'Copiers': ['Canon Image Class', 'Xerox WorkCentre'],
    'Accessories': ['Logitech Keyboard', 'Microsoft Wireless Mouse'],
    'Machines': ['Hewlett-Packard Printer', 'Epson Scanner']
}

# Dictionnaire de correspondance État -> Code
state_to_code = {
    'Alabama': 'AL', 'Alaska': 'AK', 'Arizona': 'AZ', 'Arkansas': 'AR', 'California': 'CA',
    'Colorado': 'CO', 'Connecticut': 'CT', 'Delaware': 'DE', 'Florida': 'FL', 'Georgia': 'GA',
    'Hawaii': 'HI', 'Idaho': 'ID', 'Illinois': 'IL', 'Indiana': 'IN', 'Iowa': 'IA',
    'Kansas': 'KS', 'Kentucky': 'KY', 'Louisiana': 'LA', 'Maine': 'ME', 'Maryland': 'MD',
    'Massachusetts': 'MA', 'Michigan': 'MI', 'Minnesota': 'MN', 'Mississippi': 'MS', 'Missouri': 'MO',
    'Montana': 'MT', 'Nebraska': 'NE', 'Nevada': 'NV', 'New Hampshire': 'NH', 'New Jersey': 'NJ',
    'New Mexico': 'NM', 'New York': 'NY', 'North Carolina': 'NC', 'North Dakota': 'ND', 'Ohio': 'OH',
    'Oklahoma': 'OK', 'Oregon': 'OR', 'Pennsylvania': 'PA', 'Rhode Island': 'RI', 'South Carolina': 'SC',
    'South Dakota': 'SD', 'Tennessee': 'TN', 'Texas': 'TX', 'Utah': 'UT', 'Vermont': 'VT',
    'Virginia': 'VA', 'Washington': 'WA', 'West Virginia': 'WV', 'Wisconsin': 'WI', 'Wyoming': 'WY'
}

# États disponibles avec leurs codes
available_states = ['California', 'Texas', 'New York', 'Florida', 'Illinois',
                    'Pennsylvania', 'Ohio', 'Georgia', 'North Carolina', 'Michigan']

# Générer les catégories
categories = np.random.choice(['Furniture', 'Office Supplies', 'Technology'], n, p=[0.4, 0.4, 0.2])

# Générer les sous-catégories et produits en fonction des catégories
sub_cats = []
prod_names = []

for category in categories:
    sub_cat = np.random.choice(sub_categories[category])
    sub_cats.append(sub_cat)
    prod_names.append(np.random.choice(products[sub_cat]))

# Données générées
data = {
    'Order ID': [f'CA-{2014+i//1000}-{i:06d}' for i in range(10000, 10000+n)],
    'Order Date': np.random.choice(dates, n),
    'Ship Date': None,
    'Customer ID': [f'CUST-{np.random.randint(1000, 9999)}' for _ in range(n)],
    'Customer Name': ['Customer ' + str(i) for i in range(1, n+1)],
    'Segment': np.random.choice(['Consumer', 'Corporate', 'Home Office'], n, p=[0.5, 0.3, 0.2]),
    'Country': ['United States'] * n,
    'City': np.random.choice(['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'], n),
    'State': np.random.choice(available_states, n),
    'State_Code': None,  # Sera rempli plus tard
    'Postal Code': np.random.randint(10000, 99999, n),
    'Region': np.random.choice(['West', 'East', 'Central', 'South'], n),
    'Category': categories,
    'Sub-Category': sub_cats,
    'Product Name': prod_names,
    'Sales': np.random.exponential(500, n).round(2),
    'Quantity': np.random.randint(1, 15, n),
    'Discount': np.random.uniform(0, 0.3, n).round(2),
    'Profit': None
}

df = pd.DataFrame(data)

# Calculs additionnels
df['Ship Date'] = df['Order Date'] + pd.to_timedelta(np.random.randint(5, 11, n), unit='D')
df['Profit'] = (df['Sales'] * (1 - df['Discount']) * np.random.uniform(0.1, 0.4, n)).round(2)
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Order Month'] = df['Order Date'].dt.to_period('M').astype(str)
df['Profit Margin'] = (df['Profit'] / df['Sales'] * 100).round(2)

# Ajouter les codes d'état
df['State_Code'] = df['State'].map(state_to_code)

print(f"✅ Dataset créé : {df.shape[0]} lignes")
print(f"✅ États avec codes : {df['State_Code'].unique()}")

# === 2. CALCUL DES KPI ===
total_sales = df['Sales'].sum()
total_profit = df['Profit'].sum()
avg_margin = (total_profit / total_sales * 100) if total_sales > 0 else 0
total_orders = df['Order ID'].nunique()

print(f"\n📊 KPI CALCULÉS :")
print(f"   • CA Total : ${total_sales:,.0f}")
print(f"   • Profit Total : ${total_profit:,.0f}")
print(f"   • Marge Moyenne : {avg_margin:.1f}%")
print(f"   • Commandes : {total_orders:,}")

# === 3. PRÉPARATION DES DONNÉES POUR LES GRAPHIQUES ===
print("\n📈 Préparation des données pour les graphiques...")

# Données pour le graphique 1 (évolution mensuelle)
monthly_sales = df.groupby('Order Month').agg({
    'Sales': 'sum',
    'Profit': 'sum'
}).reset_index()

# Données pour le graphique 2 (catégories)
category_sales = df.groupby(['Category', 'Sub-Category']).agg({
    'Sales': 'sum',
    'Profit': 'sum'
}).reset_index().sort_values('Sales', ascending=False)

# Données pour le graphique 3 (carte géographique - CORRIGÉ)
state_sales = df.groupby(['State', 'State_Code']).agg({
    'Sales': 'sum',
    'Profit': 'sum',
    'Order ID': 'nunique'
}).reset_index()

print(f"\n✅ Données carte préparées : {len(state_sales)} états")
print(f"   Exemple : {state_sales[['State', 'State_Code', 'Sales']].head().to_string(index=False)}")

# Données pour le graphique 4 (top produits)
top_products = df.groupby('Product Name').agg({
    'Sales': 'sum',
    'Profit': 'sum',
    'Order ID': 'nunique'
}).reset_index()
top_products = top_products.nlargest(10, 'Sales')

# === 4. AFFICHAGE DES GRAPHIQUES INDIVIDUELS ===
print("\n" + "="*60)
print("📊 AFFICHAGE DES GRAPHIQUES INDIVIDUELS")
print("="*60)

# Graphique 1 : Évolution mensuelle
print("\n✅ Graphique 1 : Évolution mensuelle des ventes")
fig1 = go.Figure()
fig1.add_trace(go.Scatter(
    x=monthly_sales['Order Month'],
    y=monthly_sales['Sales'],
    mode='lines+markers',
    name='Ventes',
    line=dict(color='blue', width=3),
    marker=dict(size=8)
))
fig1.update_layout(
    title='📈 Évolution Mensuelle des Ventes',
    xaxis_title='Mois',
    yaxis_title='Ventes ($)',
    height=500,
    showlegend=True
)
fig1.show()

# Graphique 2 : Répartition par catégorie
print("\n✅ Graphique 2 : Répartition par catégorie")
fig2 = px.sunburst(
    category_sales,
    path=['Category', 'Sub-Category'],
    values='Sales',
    title='📊 Répartition des Ventes (Sunburst)',
    color='Sales',
    color_continuous_scale='Blues',
    hover_data=['Profit']
)
fig2.update_layout(height=500)
fig2.show()

# Graphique 3 : Carte géographique USA - VERSION CORRIGÉE
print("\n✅ Graphique 3 : Carte USA corrigée")
print(f"   États à afficher : {len(state_sales)} états")

# Créer la carte avec les codes d'état
fig3 = go.Figure(data=go.Choropleth(
    locations=state_sales['State_Code'],  # Utiliser les codes d'état
    locationmode='USA-states',  # Mode USA
    z=state_sales['Sales'].astype(float),  # Valeurs numériques
    text=state_sales.apply(
        lambda row: f"<b>{row['State']}</b> ({row['State_Code']})<br>"
                   f"Ventes: ${row['Sales']:,.0f}<br>"
                   f"Profit: ${row['Profit']:,.0f}<br>"
                   f"Commandes: {row['Order ID']}",
        axis=1
    ),
    colorscale='Blues',
    colorbar_title="Ventes ($)",
    marker_line_color='white',
    hoverinfo='text'
))

fig3.update_layout(
    title_text='🌍 Carte des Ventes par État (USA)',
    geo=dict(
        scope='usa',
        projection=go.layout.geo.Projection(type='albers usa'),
        showlakes=True,
        lakecolor='rgb(255, 255, 255)',
        bgcolor='rgba(0,0,0,0)',
        subunitcolor='white',
        showland=True,
        landcolor='lightgray'
    ),
    height=500
)

# Ajouter les noms des états manuellement
for i, row in state_sales.iterrows():
    fig3.add_trace(go.Scattergeo(
        lon=[None],  # Nous n'avons pas de coordonnées exactes
        lat=[None],
        text=[row['State_Code']],
        mode='text',
        showlegend=False,
        textfont=dict(color='black', size=10),
        hoverinfo='skip'
    ))

fig3.show()

# Graphique 4 : Top 10 produits
print("\n✅ Graphique 4 : Top 10 produits")
fig4 = go.Figure()
fig4.add_trace(go.Bar(
    y=top_products['Product Name'],
    x=top_products['Sales'],
    orientation='h',
    marker_color='orange',
    text=top_products['Sales'].apply(lambda x: f'${x:,.0f}'),
    textposition='auto',
    name='Ventes'
))

fig4.update_layout(
    title='🏆 Top 10 Produits par Ventes',
    xaxis_title='Ventes ($)',
    yaxis_title='Produit',
    height=500,
    yaxis={'categoryorder': 'total ascending'}
)
fig4.show()

# === 5. CRÉATION DU DASHBOARD UNIFIÉ AVEC CARTE ===
print("\n" + "="*60)
print("📊 DASHBOARD COMPLET AVEC CARTE USA")
print("="*60)

# Créer une figure avec subplots (simplifiée pour éviter les conflits)
fig_dashboard = make_subplots(
    rows=2, cols=2,
    subplot_titles=(
        '📈 Évolution Mensuelle des Ventes',
        '📊 Top 10 Produits',
        '📦 Ventes par Catégorie',
        '🌍 Carte des Ventes USA'
    ),
    specs=[
        [{"type": "scatter"}, {"type": "bar"}],
        [{"type": "bar"}, {"type": "choropleth"}]
    ],
    vertical_spacing=0.15,
    horizontal_spacing=0.1
)

# Graphique 1 : Évolution mensuelle
fig_dashboard.add_trace(
    go.Scatter(
        x=monthly_sales['Order Month'],
        y=monthly_sales['Sales'],
        mode='lines+markers',
        name='Ventes',
        line=dict(color='blue', width=3)
    ),
    row=1, col=1
)

# Graphique 2 : Top produits
fig_dashboard.add_trace(
    go.Bar(
        y=top_products['Product Name'].head(10),
        x=top_products['Sales'].head(10),
        orientation='h',
        name='Top Produits',
        marker_color='orange',
        text=top_products['Sales'].head(10).apply(lambda x: f'${x:,.0f}'),
        textposition='auto'
    ),
    row=1, col=2
)

# Graphique 3 : Ventes par catégorie
category_summary = df.groupby('Category')['Sales'].sum().reset_index()
fig_dashboard.add_trace(
    go.Bar(
        x=category_summary['Category'],
        y=category_summary['Sales'],
        name='Par Catégorie',
        marker_color=['#FF9999', '#66B2FF', '#99FF99'],
        text=category_summary['Sales'].apply(lambda x: f'${x:,.0f}'),
        textposition='auto'
    ),
    row=2, col=1
)

# Graphique 4 : Carte USA - VERSION SIMPLIFIÉE
fig_dashboard.add_trace(
    go.Choropleth(
        locations=state_sales['State_Code'],
        locationmode='USA-states',
        z=state_sales['Sales'].astype(float),
        colorscale='Blues',
        colorbar_title="Ventes ($)",
        showscale=True,
        name='Ventes par État',
        hoverinfo='location+z'
    ),
    row=2, col=2
)

# Configuration de la géographie pour la carte
fig_dashboard.update_geos(
    row=2, col=2,
    scope='usa',
    projection_type='albers usa',
    showcoastlines=True,
    coastlinecolor="White",
    showland=True,
    landcolor="lightgray",
    subunitcolor="white",
    lakecolor='rgb(255, 255, 255)'
)

# Configuration finale du dashboard
fig_dashboard.update_layout(
    height=800,
    title_text=f"📊 Dashboard Superstore - {datetime.now().strftime('%d/%m/%Y')}",
    title_font_size=20,
    title_x=0.5,
    showlegend=True,
    template='plotly_white'
)

# Personnaliser les axes
fig_dashboard.update_xaxes(title_text="Mois", row=1, col=1)
fig_dashboard.update_yaxes(title_text="Ventes ($)", row=1, col=1)

fig_dashboard.update_xaxes(title_text="Ventes ($)", row=1, col=2)
fig_dashboard.update_yaxes(title_text="Produit", row=1, col=2)

fig_dashboard.update_xaxes(title_text="Catégorie", row=2, col=1)
fig_dashboard.update_yaxes(title_text="Ventes ($)", row=2, col=1)

print("✅ Dashboard créé avec succès !")
fig_dashboard.show()

# === 6. ANALYSE STATISTIQUE ===
print("\n" + "="*60)
print("📋 ANALYSE STATISTIQUE")
print("="*60)

print(f"\n💰 PERFORMANCE FINANCIÈRE :")
print(f"   • CA Total : ${total_sales:,.0f}")
print(f"   • Profit Total : ${total_profit:,.0f}")
print(f"   • Marge : {avg_margin:.1f}%")

print(f"\n🏢 PERFORMANCE PAR CATÉGORIE :")
for category in df['Category'].unique():
    cat_sales = df[df['Category'] == category]['Sales'].sum()
    percentage = (cat_sales / total_sales * 100) if total_sales > 0 else 0
    print(f"   • {category} : ${cat_sales:,.0f} ({percentage:.1f}%)")

print(f"\n🌎 TOP 3 ÉTATS :")
top_states = state_sales.nlargest(3, 'Sales')
for i, (_, row) in enumerate(top_states.iterrows(), 1):
    print(f"   {i}. {row['State']} ({row['State_Code']}) : ${row['Sales']:,.0f}")

print(f"\n📦 PERFORMANCE OPÉRATIONNELLE :")
print(f"   • Commandes totales : {total_orders:,}")
print(f"   • Valeur moyenne par commande : ${(total_sales/total_orders):,.0f}")
print(f"   • Période analysée : {df['Order Date'].min().date()} au {df['Order Date'].max().date()}")

# === 7. EXPORT DES DONNÉES ===
print("\n" + "="*60)
print("💾 EXPORT DES RÉSULTATS")
print("="*60)

# Créer un résumé
summary_data = {
    'KPI': ['CA Total', 'Profit Total', 'Marge', 'Commandes', 'Valeur Moyenne Commande'],
    'Valeur': [
        f"${total_sales:,.0f}",
        f"${total_profit:,.0f}",
        f"{avg_margin:.1f}%",
        f"{total_orders:,}",
        f"${(total_sales/total_orders):,.0f}"
    ]
}

summary_df = pd.DataFrame(summary_data)

print("\n📋 TABLEAU DE SYNTHÈSE :")
print(summary_df.to_string(index=False))

try:
    df.to_csv('superstore_data_complete.csv', index=False)
    summary_df.to_csv('superstore_summary.csv', index=False)
    state_sales.to_csv('superstore_state_sales.csv', index=False)

    print("\n✅ Fichiers sauvegardés :")
    print("   • superstore_data_complete.csv - Données complètes")
    print("   • superstore_summary.csv - Résumé")
    print("   • superstore_state_sales.csv - Données par état")
except Exception as e:
    print(f"\n⚠️  Erreur : {e}")

print("\n" + "="*60)
print("✅ ANALYSE TERMINÉE !")
print("="*60)
print("\n🎯 RÉCAPITULATIF :")
print("   1. ✅ 4 graphiques individuels")
print("   2. ✅ 1 dashboard avec carte USA fonctionnelle")
print("   3. ✅ Codes d'état utilisés (CA, TX, NY, etc.)")
print("   4. ✅ Données exportées en CSV")
